import datetime
import math


class GCodeLogic:
    """
    Converts a set of cut/score polyline paths into a G-code program.

    Coordinate convention
    ---------------------
    All paths arrive here in *bed space* (mm), meaning (0,0) is the
    back-left corner of the bed and +Y points toward the front.
    `_apply_origin_transform()` converts those to *machine space* (the
    coordinate system the firmware expects) based on the configured origin.

    Speed convention
    ----------------
    The UI stores all speeds in **mm/s**.  G-code F-words use **mm/min**.
    `_to_mm_min()` does the conversion and `_apply_override()` applies the
    speed-override percentage that the user sets in the Speeds tab.
    Previously, the speed override setting was stored but never actually
    applied — that is now fixed.
    """

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    def generate(self, config, cut_paths, score_paths):
        """
        Build the complete G-code string from the supplied paths.

        Parameters
        ----------
        config      : dict — the full UI config dictionary
        cut_paths   : list — [ [subpath, …], … ]  (black lines)
        score_paths : list — [ [subpath, …], … ]  (red lines)

        Returns
        -------
        (gcode_str, stats)
        stats = {"distance": float mm, "time": float minutes, "tool_changes": int}
        """
        self._config = config

        # Pre-compute the things we need throughout
        self._bed_w  = float(config.get("bed_width",    300))
        self._bed_h  = float(config.get("bed_height",   200))
        self._margin = float(config.get("safety_margin", 5))
        self._origin = config.get("origin_point", "front_left")

        self._tool_offset_x = float(config.get("tool_offset_x", 0))
        self._tool_offset_y = float(config.get("tool_offset_y", 0))

        # Speed override (%) — clamp to [1, 200]
        try:
            override_pct = float(config.get("speed_override", 100) or 100)
        except ValueError:
            override_pct = 100.0
        self._override = max(1.0, min(200.0, override_pct))

        # Remove duplicate paths before doing anything else
        cut_paths   = self._dedup_paths(cut_paths   or [])
        score_paths = self._dedup_paths(score_paths or [])

        z_mode = config.get("z_mode", "servo")

        body   = []
        stats  = {"distance": 0.0, "time": 0.0, "tool_changes": 0}

        # Score paths first (pen/blade light pass), then cut
        if score_paths:
            body.append("; --- Scoring Paths ---")
            lines, s = self._process_paths(score_paths, "scoring", z_mode)
            body.extend(lines)
            self._add_stats(stats, s)

        if cut_paths:
            body.append("; --- Cutting Paths ---")
            lines, s = self._process_paths(cut_paths, "cutting", z_mode)
            body.extend(lines)
            self._add_stats(stats, s)

        # Expand template placeholders in start/end G-code
        start_gcode = self._expand_template(config.get("start_gcode", ""))
        end_gcode   = self._expand_template(config.get("end_gcode",   ""))

        now    = datetime.datetime.now()
        header = (
            "; Generated by JD CNC Gcode Generator\n"
            f"; at {now.strftime('%H:%M:%S %d/%m/%y')}\n\n"
        )

        gcode = header + "\n".join([start_gcode] + body + [end_gcode])
        return gcode, stats

    def check_paths_in_bounds(self, config, cut_paths, score_paths):
        """
        Return True if every point in every path, after applying the origin
        transform, falls within the bed boundaries (respecting the safety
        margin).  Returns False and a brief message if any point is outside.

        This is the single, authoritative OOB check.  Previously there were
        three separate copies of this logic scattered across gcode_generator.py
        and gcode_logic.py, and they all ran the check on *pre-transform*
        coordinates, which produced false alarms for non-back-left origins.
        """
        self._config = config
        self._bed_w  = float(config.get("bed_width",    300))
        self._bed_h  = float(config.get("bed_height",   200))
        self._margin = float(config.get("safety_margin", 5))
        self._origin = config.get("origin_point", "front_left")
        self._tool_offset_x = float(config.get("tool_offset_x", 0))
        self._tool_offset_y = float(config.get("tool_offset_y", 0))

        all_paths = list(cut_paths or []) + list(score_paths or [])
        for path in all_paths:
            for sub in path:
                for pt in sub:
                    x, y = self._apply_origin_transform(pt)
                    if not (self._margin <= x <= self._bed_w - self._margin and
                            self._margin <= y <= self._bed_h - self._margin):
                        return False, (
                        )
        return True, ""

    # ------------------------------------------------------------------ #
    # Internal — path processing                                          #
    # ------------------------------------------------------------------ #

    def _process_paths(self, paths, process_type, z_mode):
        """
        Emit G-code for a list of paths in either stepper or servo Z mode.

        Returns (gcode_lines, stats).
        """
        if z_mode == "stepper":
            return self._process_stepper(paths, process_type)
        else:
            return self._process_servo(paths, process_type)

    def _process_stepper(self, paths, process_type):
        """Stepper Z mode: use G0/G1 Z moves for plunge and raise."""
        gcode = []
        stats = {"distance": 0.0, "time": 0.0, "tool_changes": 0}

        cfg = self._config
        is_scoring = (process_type == "scoring")

        # Z heights (firmware units, positive = up on most machines)
        z_cut    = cfg.get("z_stepper_cut_height",    "-2.0")
        z_score  = cfg.get("z_stepper_score_height",  "-0.5")
        z_travel = cfg.get("z_stepper_travel_height",  "5.0")
        z_work   = z_score if is_scoring else z_cut

        # Speeds: UI stores mm/s, convert to mm/min, then apply override
        cut_speed    = self._to_mm_min_override(cfg["cutting_speed"]  if not is_scoring else cfg["scoring_speed"])
        travel_speed = self._to_mm_min_override(cfg["travel_speed"])
        z_plunge_spd = self._to_mm_min_override(cfg.get("z_plunge_speed", 20))
        z_raise_spd  = self._to_mm_min_override(cfg.get("z_raise_speed",  20))

        # Format speeds without trailing decimals when they're whole numbers
        def fmt_f(v):
            return int(v) if v == int(v) else round(v, 1)

        head_is_up   = True
        last_machine = None   # last machine-space position (for travel stats)

        for path in paths:
            for sub in path:
                if not sub:
                    continue

                start_machine = self._apply_origin_transform(sub[0])

                # Track rapid travel distance for stats
                if last_machine is not None:
                    d = math.hypot(start_machine[0] - last_machine[0],
                                   start_machine[1] - last_machine[1])
                    stats["distance"] += d
                    stats["time"]     += d / travel_speed if travel_speed else 0

                # Raise if tool is still engaged
                if not head_is_up:
                    gcode.append(f"G0 F{fmt_f(z_raise_spd)} Z{z_travel}")
                    head_is_up = True

                # Rapid to start of subpath, plunge
                gcode.append(
                    f"G0 F{fmt_f(travel_speed)} "
                    f"X{start_machine[0]:.3f} Y{start_machine[1]:.3f}"
                )
                gcode.append(f"G1 F{fmt_f(z_plunge_spd)} Z{z_work}")
                head_is_up = False
                stats["tool_changes"] += 1

                # Cut along the subpath
                last_machine = start_machine
                for pt in sub[1:]:
                    p = self._apply_origin_transform(pt)
                    d = math.hypot(p[0] - last_machine[0], p[1] - last_machine[1])
                    stats["distance"] += d
                    stats["time"]     += d / cut_speed if cut_speed else 0
                    gcode.append(
                        f"G1 F{fmt_f(cut_speed)} X{p[0]:.3f} Y{p[1]:.3f}"
                    )
                    last_machine = p

                # Raise after each subpath
                gcode.append(f"G0 F{fmt_f(z_raise_spd)} Z{z_travel}")
                head_is_up = True
                last_machine = self._apply_origin_transform(sub[-1])

        return gcode, stats

    def _process_servo(self, paths, process_type):
        """Servo Z mode: use M280 commands to raise/lower the blade/pen."""
        gcode = []
        stats = {"distance": 0.0, "time": 0.0, "tool_changes": 0}

        cfg = self._config
        is_scoring = (process_type == "scoring")

        servo_work   = cfg["servo_score"]   if is_scoring else cfg["servo_cut"]
        servo_travel = cfg["servo_travel"]

        try:
            servo_delay = float(cfg.get("servo_delay", "") or 200)
        except ValueError:
            servo_delay = 200.0

        cut_speed    = self._to_mm_min_override(cfg["scoring_speed"] if is_scoring else cfg["cutting_speed"])
        travel_speed = self._to_mm_min_override(cfg["travel_speed"])

        def fmt_f(v):
            return int(v) if v == int(v) else round(v, 1)

        last_machine = None

        for path in paths:
            for sub in path:
                if not sub:
                    continue

                start_machine = self._apply_origin_transform(sub[0])

                if last_machine is not None:
                    d = math.hypot(start_machine[0] - last_machine[0],
                                   start_machine[1] - last_machine[1])
                    stats["distance"] += d
                    stats["time"]     += d / travel_speed if travel_speed else 0

                # Raise, rapid to start, lower
                gcode.append(f"M280 P0 S{servo_travel} ; Tool up (travel)")
                gcode.append(
                    f"G0 F{fmt_f(travel_speed)} "
                    f"X{start_machine[0]:.3f} Y{start_machine[1]:.3f}"
                )
                gcode.append(f"M280 P0 S{servo_work} ; Tool {process_type}")
                gcode.append(f"G4 P{int(servo_delay)} ; Wait for servo")
                stats["tool_changes"] += 1

                # Cut
                last_machine = start_machine
                for pt in sub[1:]:
                    p = self._apply_origin_transform(pt)
                    d = math.hypot(p[0] - last_machine[0], p[1] - last_machine[1])
                    stats["distance"] += d
                    stats["time"]     += d / cut_speed if cut_speed else 0
                    gcode.append(
                        f"G1 F{fmt_f(cut_speed)} X{p[0]:.3f} Y{p[1]:.3f}"
                    )
                    last_machine = p

                # Leave tool up at end of subpath
                gcode.append(f"M280 P0 S{servo_travel} ; Tool up (travel)")
                last_machine = self._apply_origin_transform(sub[-1])

        return gcode, stats

    # ------------------------------------------------------------------ #
    # Internal — coordinate transform                                     #
    # ------------------------------------------------------------------ #

    def _apply_origin_transform(self, point):
        """
        Convert a point from bed space (mm, back-left origin, +Y = front)
        to machine space, based on the configured origin setting.

        Tool offsets are applied first, then the origin flip/shift.

        NOTE: No clamping is done here.  Clamping silently eats geometry
        that's near the edge and makes it look like the cut ran fine when
        it actually got truncated.  Out-of-bounds detection is handled
        separately by check_paths_in_bounds() so the user gets an explicit
        warning rather than a silent wrong cut.
        """
        x = point[0] + self._tool_offset_x
        y = point[1] + self._tool_offset_y

        origin = self._origin
        bw = self._bed_w
        bh = self._bed_h

        if origin == "front_left":
            # Machine (0,0) is front-left; Y increases toward the back
            # Bed space +Y is toward the front, so Y flips
            return (x, bh - y)
        elif origin == "front_right":
            return (bw - x, bh - y)
        elif origin == "back_left":
            # Machine (0,0) is back-left; no flip needed
            return (x, y)
        elif origin == "back_right":
            return (bw - x, y)
        elif origin == "center":
            # Machine (0,0) is bed center
            return (x - bw / 2, y - bh / 2)
        else:
            return (x, y)

    # ------------------------------------------------------------------ #
    # Internal — helpers                                                  #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _to_mm_min(val):
        """Convert a speed value from mm/s to mm/min."""
        try:
            return float(val) * 60.0
        except (ValueError, TypeError):
            return 0.0

    def _to_mm_min_override(self, val):
        """Convert mm/s → mm/min and apply the speed-override percentage."""
        return self._to_mm_min(val) * self._override / 100.0

    @staticmethod
    def _dedup_paths(paths):
        """
        Remove exact-duplicate paths.  Two paths are duplicates if all their
        subpoints round to the same values at 3 decimal places.
        """
        seen   = set()
        unique = []
        for path in paths:
            key = tuple(
                tuple((round(x, 3), round(y, 3)) for x, y in sub)
                for sub in path
            )
            if key not in seen:
                seen.add(key)
                unique.append(path)
        return unique

    @staticmethod
    def _add_stats(total, partial):
        for k in total:
            total[k] += partial[k]

    def _expand_template(self, template):
        """
        Expand {key} placeholders in start/end G-code templates using the
        current config.  Unknown keys are left as-is rather than raising.
        """
        try:
            return template.format_map(_SafeFormatMap(self._config))
        except Exception:
            return template


class _SafeFormatMap(dict):
    """A dict subclass that returns the original {key} string for missing keys."""
    def __missing__(self, key):
        return "{" + key + "}"